### ISSUE TITLE
Installation fails in brand new Pharo8 image

### ISSUE THREAD

**Issue by FrankB2** [PharoJS/PharoJS#22]
Hello,

I have a brand new Pharo8 image, just freshly installed manually, 
![200213-PharoJS-Install-Err1](https://user-images.githubusercontent.com/61018973/74450738-e13df000-4e7e-11ea-8813-7b29ad3cec98.PNG)
![200213-PharoJS-Install-Err1](https://user-images.githubusercontent.com/61018973/74450777-ee5adf00-4e7e-11ea-92a8-0ba6eea40de8.PNG)
![200213-PharoJS-Install-Err1](https://user-images.githubusercontent.com/61018973/74450792-f581ed00-4e7e-11ea-92df-48d1d5ffb54d.PNG)

and I wanted to install PharoJS using. 
Metacello new
  baseline: 'PharoJS';
  repository: 'github://PharoJS/PharoJS';
  load
but this crashes. See the attached screenshot.

Is there any alternative method available? 
(Note: I am very experienced in Smalltalk but only very little in Pharo)

Regards
Frank
![200213-PharoJS-Install-Err1](https://user-images.githubusercontent.com/61018973/74450941-219d6e00-4e7f-11ea-9aad-63d435421b34.PNG)

**Comment by FrankB2** [comment]
What a stupid software this Github!.  First time I used it. It did not show that the file was inserted and I see no way to edit or remove the copies.  Seems this is as good as Microsoft Skype!

**Comment by bouraqadi** [comment]
Frank which OS are you running. In some libgit seem to have an issue with file paths that might include parenthesis see issue #20. Please try renaming your image in the launcher.

BTW, use a Pharo 7 image. PharoJS hasn't been ported yet to the latest Pharo release.

**Comment by FrankB2** [comment]
Bon soir,

thank you very much for the very quick reply!

I am on Win7. I tried the import with Gofer and it worked well until 
quite then end when there was an update needed for the (I think) Zinc 
tools.

But for the paths, this may be correct, because I first used the 
PahorLauncher, which raped me by installing all on C:\ drive without any 
asking. Very bad behaviour. So made a "conventional" install where it 
belongs.

But don't worry, I will try the same with Pharo-7 again.

I will report to you if that worked.

Only in case it may be of interest to you, I am enclosing the Screenshot 
of the error.

A bientôt
Frank




------ Originalnachricht ------
Von: "Noury Bouraqadi" <notifications@github.com>
An: "PharoJS/PharoJS" <PharoJS@noreply.github.com>
Cc: "FrankB2" <frank.berger.software@web.de>; "State change" 
<state_change@noreply.github.com>
Gesendet: 13.02.2020 19:04:47
Betreff: Re: [PharoJS/PharoJS] Installation fails in brand new Pharo8 
image (#22)

**Comment by FrankB2** [comment]
Hello,

I know this is not your subject or fault, but there is no chance to find 
a Pharo-7 to download. Only FYI, I just posted this on the forum:

-----------------------------
Hello,

after failing to import PharoJS in a virgin Pharo-8 image, I received 
very quicky a very friendly support email recommending me to try the 
same with Pharo-7.

But WTF can I download Pharo-7?

There is nothing on the download page, not even a link to older 
versions. Why is that so user-hostile???

I search via the Big-G Stasi search engine - no result either.

This is extremely annoying!

I have been on this for close to three hours only to get a sample image 
running.

Greatest user experience!
----------------------------------------------------------

Just in case you know the guy who makes this website, please let hom 
know. Tx

Regards
Frank

------ Originalnachricht ------
Von: "Noury Bouraqadi" <notifications@github.com>
An: "PharoJS/PharoJS" <PharoJS@noreply.github.com>
Cc: "FrankB2" <frank.berger.software@web.de>; "State change" 
<state_change@noreply.github.com>
Gesendet: 13.02.2020 19:04:47
Betreff: Re: [PharoJS/PharoJS] Installation fails in brand new Pharo8 
image (#22)

**Comment by bouraqadi** [comment]
Frank, you should install pharo launcher. It's now the default, that you get from Pharo's download page http://pharo.org/download. It allows you pick the image version of your choice, and downloads the required VM automatically.

**Comment by bouraqadi** [comment]
BTW, you can join the PharoJS slack channel for help with PharoJS. Check out the PharoJS FAQ https://pharojs.github.io/faq.html

**Comment by FrankB2** [comment]
Thank you again for the help,

but I had done this in the very first place. But this tool rapes me by 
deciding itself where to install Pharo and it does so on c:\ users etc. 
I made a posting on this but that was not published.

My C is a small SSD. Never, ever do I have anything on C except the OS. 
I cannot undestand how somebody thinks he can decide for the user where 
to install the software. So sick!

So I guess, there will be path problems, if I copy this to where it 
belongs on my computer.

Sorry, to bug you wth this. BTW: I had similar problems a few years ago, 
when I tried Pharo.

Main poblem is where to DL a Pharo-7?

Regards
Frank




------ Originalnachricht ------
Von: "Noury Bouraqadi" <notifications@github.com>
An: "PharoJS/PharoJS" <PharoJS@noreply.github.com>
Cc: "FrankB2" <frank.berger.software@web.de>; "State change" 
<state_change@noreply.github.com>
Gesendet: 13.02.2020 20:03:32
Betreff: Re: [PharoJS/PharoJS] Installation fails in brand new Pharo8 
image (#22)

**Comment by FrankB2** [comment]
Tx, I have been there at the beginning, DL the Launcher, failed because 
of the Launcher deciding about the path.

It says there "Pharo 7 is avaílable on Pharo 7" - great BS what is "on 
Pharo 7". There is not a single DL link on Pharo.org.


------ Originalnachricht ------
Von: "Noury Bouraqadi" <notifications@github.com>
An: "PharoJS/PharoJS" <PharoJS@noreply.github.com>
Cc: "FrankB2" <frank.berger.software@web.de>; "State change" 
<state_change@noreply.github.com>
Gesendet: 13.02.2020 20:06:25
Betreff: Re: [PharoJS/PharoJS] Installation fails in brand new Pharo8 
image (#22)

**Comment by bouraqadi** [comment]
I guess, you should send your issue to the pharo mailing list or to the pharo Discord team. See http://pharo.org/community

**Comment by FrankB2** [comment]
Merci, c'est ce que j'ai déja fait!

Bon soir!

------ Originalnachricht ------
Von: "Noury Bouraqadi" <notifications@github.com>
An: "PharoJS/PharoJS" <PharoJS@noreply.github.com>
Cc: "FrankB2" <frank.berger.software@web.de>; "State change" 
<state_change@noreply.github.com>
Gesendet: 13.02.2020 20:58:28
Betreff: Re: [PharoJS/PharoJS] Installation fails in brand new Pharo8 
image (#22)

**Comment by FrankB2** [comment]
Cher Monsieur Bouraqdi,

it failed again - three times!

I did this:

1) I started the Launcher
Choose Pharo-7-64 Bit
Let the Launcher install it on C:\ (see screenhot)

I started the image and then "do it" as you can see to import PharoJS. 
And it failed immediately.

Must be bad fate what I am experiencing with Pharo!

Translation of the German in the Scrrenshot: The statis of te handle 
does not correspond to the requested procedure.

2) I then tried Gofer again and after a couple of seconds the entire 
image was handing. I could not click anything at all. Just frozen.
I then killed the hanging image.

3) I started the virgin image again
Did the Gofer command
and same as before frozen after a few second..

Sorry, but this is frustrating.
Sorry to bug you, but I am very seriously interested in PharoJS. Could 
you do an import and just make the image available for download?

I would VERY much appreciate this.

Best regards
Frank





Pardonnée moi, it's simpler and faster for me to write in English, my 
French is quite rosty.



------ Originalnachricht ------
Von: "Noury Bouraqadi" <notifications@github.com>
An: "PharoJS/PharoJS" <PharoJS@noreply.github.com>
Cc: "FrankB2" <frank.berger.software@web.de>; "State change" 
<state_change@noreply.github.com>
Gesendet: 13.02.2020 21:46:29
Betreff: Re: [PharoJS/PharoJS] Installation fails in brand new Pharo8 
image (#22)

**Comment by bouraqadi** [comment]
Dear Frank. Can you please try the following :
1- Create a new fresh image
2- Give it a one word name (e.g. PharoJS)
3- Evaluate the install statement 

PS. PharoJS is a project with developers and users from around the world. English is the language we use. No worries about French ;-)

**Comment by bouraqadi** [comment]
BTW, I'm setting up a Pharo 7 image with PharoJS. Will let you know once it's available, and where to get it :-)

Meanwhile, please join the SLACK group where you can discuss with the community. See https://pharojs.github.io/faq.html#help

**Comment by FrankB2** [comment]
Thank you very much. I amjust about to try again!


------ Originalnachricht ------
Von: "Noury Bouraqadi" <notifications@github.com>
An: "PharoJS/PharoJS" <PharoJS@noreply.github.com>
Cc: "FrankB2" <frank.berger.software@web.de>; "State change" 
<state_change@noreply.github.com>
Gesendet: 14.02.2020 09:23:23
Betreff: Re: [PharoJS/PharoJS] Installation fails in brand new Pharo8 
image (#22)

**Comment by FrankB2** [comment]
Hello Noury,

same thing as before:

1) See screenshot
2) With Gofer freeing again

Sorry!


------ Originalnachricht ------
Von: "Noury Bouraqadi" <notifications@github.com>
An: "PharoJS/PharoJS" <PharoJS@noreply.github.com>
Cc: "FrankB2" <frank.berger.software@web.de>; "State change" 
<state_change@noreply.github.com>
Gesendet: 14.02.2020 09:17:01
Betreff: Re: [PharoJS/PharoJS] Installation fails in brand new Pharo8 
image (#22)

**Comment by FrankB2** [comment]
Addendum:

There are sill blanks in the path but I cannot change this except 
manually, because this stupip installer dictates where to install Pharo 
(what a horrible stupid idea!). So if the whole filename causes this, 
this is a dead-lock situation.

I just cannot understand why and how one can create such an installer! 
Totally beyond my comprehension. Pardon!



------ Originalnachricht ------
Von: "Frank Berger Software" <frank.berger.software@web.de>
An: "PharoJS/PharoJS" 
<reply@reply.github.com>
Gesendet: 14.02.2020 09:28:03
Betreff: Re[2]: [PharoJS/PharoJS] Installation fails in brand new Pharo8 
image (#22)

**Comment by FrankB2** [comment]
FYI: I have sent an email to pharojs@scs.ryerson.ca asking for an 
account


------ Originalnachricht ------
Von: "Noury Bouraqadi" <notifications@github.com>
An: "PharoJS/PharoJS" <PharoJS@noreply.github.com>
Cc: "FrankB2" <frank.berger.software@web.de>; "State change" 
<state_change@noreply.github.com>
Gesendet: 14.02.2020 09:23:23
Betreff: Re: [PharoJS/PharoJS] Installation fails in brand new Pharo8 
image (#22)

**Comment by bouraqadi** [comment]
Frank, 

Just it does make sens to make things parameterizable. You should get in touch with the Pharo launcher developers and give them your feedback. But, please bear in mind that every software can be improved.  Knowing that Pharo is an open source project, with contributors that do it for free, and have another occupation/day-job, what we have has a lot of value. Just compare to other bigger communities. 

Anyway, this conversation is unrelated to PharoJS. Let's move it elsewhere.

**Comment by FrankB2** [comment]
Well, Noury,

thank you but I better won't get in touch with them, because my 
experiences are far tooo bad. You should know that I had made very 
similar experiences with Pharo and PharoJS a little over two years ago.

But first, the available info about PharoJS looked so much better now 
and second I do NOW have an urgent need to some working solution to 
convert Smalltalk into JS, bcause I simply refuse to waste my time in 
conventional JS programming. This JS programming is so stoneage (I spent 
almost a year on this in 2012) and second all my definitions etc are in 
Smalltalk. I even define models, DLL and major parts of the UI from 
"description data" and I don't feel like replicating this into 
JavaScript. My own framwork has 10.000+ classes and 200K+ methods.

Unfotunaly, the Orca project by Hasso-Plattner institute is dead (I 
spoke with the professor)
See http://www.hpi.uni-potsdam.de/hirschfeld/projects/orca/index.html  
very interesting!
The documentation that I read two years ago as well as the concepts 
seemed to me "brilliant".

I have major product ideas and plans (not only) to web related products 
and I will definitely not never ever use Seaside (horrible in my view).

It's the psychology of groups: An outsider and newbie to the flock comes 
in and first thing he does is critizising. Even though all my critics 
were meant as constructive proposals with very good arguments and 
although in this case it would be absolutely justified, group members 
just don't like that and then comes the argument "it's all done for 
free", which I cannot see as an excuse to produce BS.

Therefore, my frustration was at the highest possible level, because 
just the same happened again to me this week what I had encountered two 
years ago.

OK, this just as background. I will now try to get your image to work 
and let you know what I encounter.

And again, thank you very much for your help.

As a personal remark: I went to school in Paris for 6 months and another 
6 month in Lausanne and in my first profession I used French daily and 
in my generation almost every well educated German spoke at least some 
French, so I am not a friend of turning everything into English but I am 
rather on the side of Charles de Gaulle - but yes, that is "tempi 
passati", I know.

Best regards from Slovakia






------ Originalnachricht ------
Von: "Noury Bouraqadi" <notifications@github.com>
An: "PharoJS/PharoJS" <PharoJS@noreply.github.com>
Cc: "FrankB2" <frank.berger.software@web.de>; "State change" 
<state_change@noreply.github.com>
Gesendet: 14.02.2020 09:58:55
Betreff: Re: [PharoJS/PharoJS] Installation fails in brand new Pharo8 
image (#22)
