### ISSUE TITLE
Association equality test fails

### ISSUE THREAD

**Issue by Ironirc** [PharoJS/PharoJS#25]
```
| assoc |
assoc := 'ivo' -> 1.
assoc = assoc ifFalse: [ self error: 'assocs not equal?' ]
```

**Comment by bouraqadi** [comment]
The last commit to branch 25-Association-equality-test-fails fixes the issue. We'll be integrating it soon to the master branch

**Comment by dvmason** [comment]
Fix integrated. All tests pass
