### ISSUE TITLE
Identity dictionary serialization test fails sometimes

### ISSUE THREAD

**Issue by bouraqadi** [PharoJS/PharoJS#59]
Dictionaries are unordered. The test `PhxBridgedJsonSerialisationTests>>testSerializeIdentityDictionary` relies on a fixed order. This is why it fails sometimes, but not always

**Comment by ironirc** [comment]
@bouraqadi Hi Noury, didn't you already address this issue with test methods: `testSerializeIdentityDictionary1Entry` and `testSerializeIdentityDictionary2Entries` ?
