### ISSUE TITLE
unexpected behaviour of PjIdentityDictionary>>at:ifAbsentPut:

### ISSUE THREAD

**Issue by Ironirc** [PharoJS/PharoJS#65]
the argument of ifAbsentPut: should be a block instead of anObject
I think the correct implementation would be:
```
PjIdentityDictionary>>at: key ifAbsentPut: aBlock
   | value | 	
   value := self at: key. 
   value ifNil: [^self at: key put: aBlock value]. 
   ^value
   ```
All existing tests (PjIdentityDictionaryTest) turn green with this new behaviour,
but that's probably just pure luck, because  "42 value = 42"

**Comment by dvmason** [comment]
Closing
