### ISSUE TITLE
provide a way to define javascript method aliases (without js_ prefix)

### ISSUE THREAD

**Issue by Ironirc** [PharoJS/PharoJS#68]
using a pragma might be a proper way to define the aliases
```
foo: foo bar: bar
    <jsAliases: #(fooBar foo-bar)>
    ^foo + bar
```

**Comment by dvmason** [comment]
Fixed. You can use <jsAlias: #someJSName>

If you need multiple aliases, you can add any number of ' and: #otherName'.  e.g. <jsAlias: #jsName1 and: #jsName2 and: #jsName3>
