### ISSUE TITLE
Problem with test suites on Pharo9/Windows 10 (about 50% of tests fail)

### ISSUE THREAD

**Issue by ironirc** [PharoJS/PharoJS#74]
Otoh, running invidual tests works fine.

After some investigation I found that the problem occurs during PjBridge>>#resetClient.
After `self sendMessage: PjMessageReload new` the client reloads and reconnects with a new websocket. In effect `PjBridgeServer>>#value:` gets called with a new websocket.
This sets the instvar `webSocket` of the `PjBridgeServer` instance. In my problem case, this happens before the previous websocket gets disconnected. So when the previous websocket disconnects, this gets caught by the exception handler in `PjBridgeServer>>#value:` which in turn sets instvar `webSocket` of the `PjBridgeServer` back to `nil`. Because of this, communication towards the client is cut off.

One possible solution is to just ignore the error:

```
on: Error
do: [ "self webSocket: nil" ]
```

**Comment by bouraqadi** [comment]
Fixed by PR #77
