### ISSUE TITLE
Pharo 9 compatibility package needed

### ISSUE THREAD

**Issue by astares** [PharoJS/PharoJS#83]
The baseline has a definition that for Pharo 9 a compatibility package for Pharo 8 gets loaded. This looks not clean:

![image](https://user-images.githubusercontent.com/5980033/152305711-c286c425-ef0f-4d76-8f2f-79887f308a94.png)

There are now als changes in OCAbstractMethodScope in Pharo 9 release that will affect PharoJS and makes it necessary to introduce a Pharo 9 specific compatibility package.

**Comment by astares** [comment]
Pharo 7:
![image](https://user-images.githubusercontent.com/5980033/152305771-cc87f8f3-d534-41ed-98f7-7b7e89189668.png)

Pharo 8:
![image](https://user-images.githubusercontent.com/5980033/152305809-ab706c32-414f-4af5-9c82-f4267858dc53.png)

Pharo 9 (**broken**)
![image](https://user-images.githubusercontent.com/5980033/152305852-379f2338-25f8-4172-9709-36c28f7af78a.png)

**Comment by astares** [comment]
So there is no ivar "thisContextVar" anymore in class OCAbstractMethodScope for Pharo9. Also the class OCThisContextVariable is deprecated in that release.

We can easily fix this using:
![image](https://user-images.githubusercontent.com/5980033/152306038-6df32f94-a83a-49d0-bd15-2dd5db595521.png)

**Comment by astares** [comment]
but because of that I need to introduce an own compatibility package for Pharo 9 additionally.

**Comment by bouraqadi** [comment]
Fixed by PR #85
