### ISSUE TITLE
PjDateAndTimeTest fails because of differences between Pharo and browser date formatting

### ISSUE THREAD

**Issue by dvmason** [PharoJS/PharoJS#99]
Parsing a date-time-string is handled differently:
1) for Pharo, the timezone is part of the object. If there is a timezone specified, Pharo remembers that timezone, else it uses the current local timezone.
2) browsers parse the string into a second offset integer relative to UTC - no timezone is remembered

When formatting a date:
1) Pharo uses the timezone in the object
2) browsers use the local timezone *on the date/time encoded in the integer* so daylight saving time is as of that date/time

This means that for todays date (and a time after 03:00), the round-trip will be the same without a timezone. With a timezone other than the current one, the strings will represent the same time, but won't be the same strings.

For other dates, with or without a timezone, the strings may differ because the browser will use the timezone in effect on that date/time (time could be relevant if daylight savings time starts or ends that day), while Pharo will use the encoded timezone (which would be the current one if not specified on the parse).

(*whew*)

**Comment by bouraqadi** [comment]
Fixed with PR#100

**Comment by bouraqadi** [comment]
Flickering again after switching to summer time

**Comment by bouraqadi** [comment]
Fixed by PR #104
